spring.application.name=backend

# 1. Quay lại dùng cổng trực tiếp (5432) cho dễ chịu, Username trở về như cũ
spring.datasource.url=jdbc:postgresql://db.zhwzksscfcymjfjghdii.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=gonduc15102005
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Ép cứng nhận diện Database là PostgreSQL (TRỊ DỨT ĐIỂM LỖI DIALECT)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# 3. Tắt khởi tạo file SQL thủ công
spring.sql.init.mode=never

# 4. Port bắt buộc cho Render
server.port=${PORT:8080}