spring.application.name=backend

# Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/haibazo_b1
spring.datasource.username=postgres
spring.datasource.password=gonduc

# Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Luôn chạy file schema.sql khi khởi động
spring.sql.init.mode=always